### ISSUE TITLE
Not work around html tags

### ISSUE THREAD

**Issue by zhangzq** [EloiseSeverin/markdown_cjk_spacing#1]
it will not insert space in below text：

`english<span>中文</span>`

**Comment by zhangzq** [comment]
Could you add an option to this?

I used https://github.com/yuex/cjk-auto-spacing before. It works perfect for me, but only for pelican. I need this plugin for mkdocs.

**Comment by EloiseSeverin** [comment]
This is by design or intended behavior.
cjk-auto-spacing rewrites the entire html, markdown_cjk_spacing affects only individual text elements.

For this reason, cjk-auto-spacing will be change
"<pre>[CJK word].txt</pre>" to "<pre>_[CJK word]_.txt_</pre>".

If you want a space around <span>, add the space explicitly.

**Comment by EloiseSeverin** [comment]
This is by design or intended behavior.
cjk-auto-spacing rewrites the entire html,
markdown_cjk_spacing affects only individual text elements.

For this reason, cjk-auto-spacing will be change
`<code>[CJK word].txt</code>` to `<code> [CJK word] .txt </pre>`.

If you want a space around <span>, add the space explicitly.

**Comment by EloiseSeverin** [comment]
This is by design or intended behavior.
cjk-auto-spacing rewrites the entire html,
markdown_cjk_spacing affects only individual text elements.

For this reason, cjk-auto-spacing will be change
`<pre>[CJK word].txt</pre>` to `<pre> [CJK word] .txt </pre>`.

If you want a space around <span>, add the space explicitly.
